package org.ys.core.model;

import java.io.Serializable;

public class CoreMenu implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 4643685674656718210L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.core_menu_id
     *
     * @mbg.generated
     */
    private Long coreMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.menu_type
     *
     * @mbg.generated
     */
    private String menuType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.menu_url
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.permission
     *
     * @mbg.generated
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.order_num
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.parent_core__menu_id
     *
     * @mbg.generated
     */
    private Long parentCoreMenuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.core_menu_id
     *
     * @return the value of core_menu.core_menu_id
     *
     * @mbg.generated
     */
    public Long getCoreMenuId() {
        return coreMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.core_menu_id
     *
     * @param coreMenuId the value for core_menu.core_menu_id
     *
     * @mbg.generated
     */
    public void setCoreMenuId(Long coreMenuId) {
        this.coreMenuId = coreMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.icon
     *
     * @return the value of core_menu.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.icon
     *
     * @param icon the value for core_menu.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.menu_name
     *
     * @return the value of core_menu.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.menu_name
     *
     * @param menuName the value for core_menu.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.menu_type
     *
     * @return the value of core_menu.menu_type
     *
     * @mbg.generated
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.menu_type
     *
     * @param menuType the value for core_menu.menu_type
     *
     * @mbg.generated
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.menu_url
     *
     * @return the value of core_menu.menu_url
     *
     * @mbg.generated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.menu_url
     *
     * @param menuUrl the value for core_menu.menu_url
     *
     * @mbg.generated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.permission
     *
     * @return the value of core_menu.permission
     *
     * @mbg.generated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.permission
     *
     * @param permission the value for core_menu.permission
     *
     * @mbg.generated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.order_num
     *
     * @return the value of core_menu.order_num
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.order_num
     *
     * @param orderNum the value for core_menu.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.parent_core__menu_id
     *
     * @return the value of core_menu.parent_core__menu_id
     *
     * @mbg.generated
     */
    public Long getParentCoreMenuId() {
        return parentCoreMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.parent_core__menu_id
     *
     * @param parentCoreMenuId the value for core_menu.parent_core__menu_id
     *
     * @mbg.generated
     */
    public void setParentCoreMenuId(Long parentCoreMenuId) {
        this.parentCoreMenuId = parentCoreMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreMenu other = (CoreMenu) that;
        return (this.getCoreMenuId() == null ? other.getCoreMenuId() == null : this.getCoreMenuId().equals(other.getCoreMenuId()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getMenuName() == null ? other.getMenuName() == null : this.getMenuName().equals(other.getMenuName()))
            && (this.getMenuType() == null ? other.getMenuType() == null : this.getMenuType().equals(other.getMenuType()))
            && (this.getMenuUrl() == null ? other.getMenuUrl() == null : this.getMenuUrl().equals(other.getMenuUrl()))
            && (this.getPermission() == null ? other.getPermission() == null : this.getPermission().equals(other.getPermission()))
            && (this.getOrderNum() == null ? other.getOrderNum() == null : this.getOrderNum().equals(other.getOrderNum()))
            && (this.getParentCoreMenuId() == null ? other.getParentCoreMenuId() == null : this.getParentCoreMenuId().equals(other.getParentCoreMenuId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCoreMenuId() == null) ? 0 : getCoreMenuId().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getMenuName() == null) ? 0 : getMenuName().hashCode());
        result = prime * result + ((getMenuType() == null) ? 0 : getMenuType().hashCode());
        result = prime * result + ((getMenuUrl() == null) ? 0 : getMenuUrl().hashCode());
        result = prime * result + ((getPermission() == null) ? 0 : getPermission().hashCode());
        result = prime * result + ((getOrderNum() == null) ? 0 : getOrderNum().hashCode());
        result = prime * result + ((getParentCoreMenuId() == null) ? 0 : getParentCoreMenuId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", coreMenuId=").append(coreMenuId);
        sb.append(", icon=").append(icon);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuType=").append(menuType);
        sb.append(", menuUrl=").append(menuUrl);
        sb.append(", permission=").append(permission);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", parentCoreMenuId=").append(parentCoreMenuId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}