package org.ys.core.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class CoreDictionariesGroupExample implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 9058037835634731394L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public CoreDictionariesGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable{
        /**
		 * 
		 */
		private static final long serialVersionUID = -5691850471930521823L;
		protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCoreDictGroupIdIsNull() {
            addCriterion("core_dict_group_id is null");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdIsNotNull() {
            addCriterion("core_dict_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdEqualTo(Long value) {
            addCriterion("core_dict_group_id =", value, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdNotEqualTo(Long value) {
            addCriterion("core_dict_group_id <>", value, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdGreaterThan(Long value) {
            addCriterion("core_dict_group_id >", value, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("core_dict_group_id >=", value, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdLessThan(Long value) {
            addCriterion("core_dict_group_id <", value, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("core_dict_group_id <=", value, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdIn(List<Long> values) {
            addCriterion("core_dict_group_id in", values, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdNotIn(List<Long> values) {
            addCriterion("core_dict_group_id not in", values, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdBetween(Long value1, Long value2) {
            addCriterion("core_dict_group_id between", value1, value2, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andCoreDictGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("core_dict_group_id not between", value1, value2, "coreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameIsNull() {
            addCriterion("dict_group_name is null");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameIsNotNull() {
            addCriterion("dict_group_name is not null");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameEqualTo(String value) {
            addCriterion("dict_group_name =", value, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameNotEqualTo(String value) {
            addCriterion("dict_group_name <>", value, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameGreaterThan(String value) {
            addCriterion("dict_group_name >", value, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("dict_group_name >=", value, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameLessThan(String value) {
            addCriterion("dict_group_name <", value, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameLessThanOrEqualTo(String value) {
            addCriterion("dict_group_name <=", value, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameLike(String value) {
            addCriterion("dict_group_name like", value, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameNotLike(String value) {
            addCriterion("dict_group_name not like", value, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameIn(List<String> values) {
            addCriterion("dict_group_name in", values, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameNotIn(List<String> values) {
            addCriterion("dict_group_name not in", values, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameBetween(String value1, String value2) {
            addCriterion("dict_group_name between", value1, value2, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupNameNotBetween(String value1, String value2) {
            addCriterion("dict_group_name not between", value1, value2, "dictGroupName");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeIsNull() {
            addCriterion("dict_group_code is null");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeIsNotNull() {
            addCriterion("dict_group_code is not null");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeEqualTo(String value) {
            addCriterion("dict_group_code =", value, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeNotEqualTo(String value) {
            addCriterion("dict_group_code <>", value, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeGreaterThan(String value) {
            addCriterion("dict_group_code >", value, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dict_group_code >=", value, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeLessThan(String value) {
            addCriterion("dict_group_code <", value, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeLessThanOrEqualTo(String value) {
            addCriterion("dict_group_code <=", value, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeLike(String value) {
            addCriterion("dict_group_code like", value, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeNotLike(String value) {
            addCriterion("dict_group_code not like", value, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeIn(List<String> values) {
            addCriterion("dict_group_code in", values, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeNotIn(List<String> values) {
            addCriterion("dict_group_code not in", values, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeBetween(String value1, String value2) {
            addCriterion("dict_group_code between", value1, value2, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupCodeNotBetween(String value1, String value2) {
            addCriterion("dict_group_code not between", value1, value2, "dictGroupCode");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescIsNull() {
            addCriterion("dict_group_desc is null");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescIsNotNull() {
            addCriterion("dict_group_desc is not null");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescEqualTo(String value) {
            addCriterion("dict_group_desc =", value, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescNotEqualTo(String value) {
            addCriterion("dict_group_desc <>", value, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescGreaterThan(String value) {
            addCriterion("dict_group_desc >", value, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescGreaterThanOrEqualTo(String value) {
            addCriterion("dict_group_desc >=", value, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescLessThan(String value) {
            addCriterion("dict_group_desc <", value, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescLessThanOrEqualTo(String value) {
            addCriterion("dict_group_desc <=", value, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescLike(String value) {
            addCriterion("dict_group_desc like", value, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescNotLike(String value) {
            addCriterion("dict_group_desc not like", value, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescIn(List<String> values) {
            addCriterion("dict_group_desc in", values, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescNotIn(List<String> values) {
            addCriterion("dict_group_desc not in", values, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescBetween(String value1, String value2) {
            addCriterion("dict_group_desc between", value1, value2, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andDictGroupDescNotBetween(String value1, String value2) {
            addCriterion("dict_group_desc not between", value1, value2, "dictGroupDesc");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdIsNull() {
            addCriterion("parent_core_dict_group_id is null");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdIsNotNull() {
            addCriterion("parent_core_dict_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdEqualTo(Long value) {
            addCriterion("parent_core_dict_group_id =", value, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdNotEqualTo(Long value) {
            addCriterion("parent_core_dict_group_id <>", value, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdGreaterThan(Long value) {
            addCriterion("parent_core_dict_group_id >", value, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_core_dict_group_id >=", value, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdLessThan(Long value) {
            addCriterion("parent_core_dict_group_id <", value, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_core_dict_group_id <=", value, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdIn(List<Long> values) {
            addCriterion("parent_core_dict_group_id in", values, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdNotIn(List<Long> values) {
            addCriterion("parent_core_dict_group_id not in", values, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdBetween(Long value1, Long value2) {
            addCriterion("parent_core_dict_group_id between", value1, value2, "parentCoreDictGroupId");
            return (Criteria) this;
        }

        public Criteria andParentCoreDictGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_core_dict_group_id not between", value1, value2, "parentCoreDictGroupId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        /**
		 * 
		 */
		private static final long serialVersionUID = 2890671736613831480L;

		protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable{
        /**
		 * 
		 */
		private static final long serialVersionUID = -4230522213698322623L;

		private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}