package org.ys.core.model;

import java.io.Serializable;

public class CoreDictionaries implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -4035017694639176176L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_dictionaries.core_dict_id
     *
     * @mbg.generated
     */
    private Long coreDictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_dictionaries.dict_code
     *
     * @mbg.generated
     */
    private String dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_dictionaries.dict_value
     *
     * @mbg.generated
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_dictionaries.core_dict_group_id
     *
     * @mbg.generated
     */
    private Long coreDictGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_dictionaries.core_dict_id
     *
     * @return the value of core_dictionaries.core_dict_id
     *
     * @mbg.generated
     */
    public Long getCoreDictId() {
        return coreDictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_dictionaries.core_dict_id
     *
     * @param coreDictId the value for core_dictionaries.core_dict_id
     *
     * @mbg.generated
     */
    public void setCoreDictId(Long coreDictId) {
        this.coreDictId = coreDictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_dictionaries.dict_code
     *
     * @return the value of core_dictionaries.dict_code
     *
     * @mbg.generated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_dictionaries.dict_code
     *
     * @param dictCode the value for core_dictionaries.dict_code
     *
     * @mbg.generated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_dictionaries.dict_value
     *
     * @return the value of core_dictionaries.dict_value
     *
     * @mbg.generated
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_dictionaries.dict_value
     *
     * @param dictValue the value for core_dictionaries.dict_value
     *
     * @mbg.generated
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_dictionaries.core_dict_group_id
     *
     * @return the value of core_dictionaries.core_dict_group_id
     *
     * @mbg.generated
     */
    public Long getCoreDictGroupId() {
        return coreDictGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_dictionaries.core_dict_group_id
     *
     * @param coreDictGroupId the value for core_dictionaries.core_dict_group_id
     *
     * @mbg.generated
     */
    public void setCoreDictGroupId(Long coreDictGroupId) {
        this.coreDictGroupId = coreDictGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreDictionaries other = (CoreDictionaries) that;
        return (this.getCoreDictId() == null ? other.getCoreDictId() == null : this.getCoreDictId().equals(other.getCoreDictId()))
            && (this.getDictCode() == null ? other.getDictCode() == null : this.getDictCode().equals(other.getDictCode()))
            && (this.getDictValue() == null ? other.getDictValue() == null : this.getDictValue().equals(other.getDictValue()))
            && (this.getCoreDictGroupId() == null ? other.getCoreDictGroupId() == null : this.getCoreDictGroupId().equals(other.getCoreDictGroupId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCoreDictId() == null) ? 0 : getCoreDictId().hashCode());
        result = prime * result + ((getDictCode() == null) ? 0 : getDictCode().hashCode());
        result = prime * result + ((getDictValue() == null) ? 0 : getDictValue().hashCode());
        result = prime * result + ((getCoreDictGroupId() == null) ? 0 : getCoreDictGroupId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", coreDictId=").append(coreDictId);
        sb.append(", dictCode=").append(dictCode);
        sb.append(", dictValue=").append(dictValue);
        sb.append(", coreDictGroupId=").append(coreDictGroupId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}