package org.ys.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ys.core.model.CoreMenu;
import org.ys.core.model.CoreMenuExample;

public interface CoreMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    long countByExample(CoreMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    int deleteByExample(CoreMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long coreMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    int insert(CoreMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    int insertSelective(CoreMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    List<CoreMenu> selectByExample(CoreMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    CoreMenu selectByPrimaryKey(Long coreMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CoreMenu record, @Param("example") CoreMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CoreMenu record, @Param("example") CoreMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CoreMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CoreMenu record);
    
    List<CoreMenu> listCoreMenusByUserId(Long coreUserId);
    
    List<CoreMenu> listCoreMenusByRoleId(Long coreRoleId);
}