package org.ys.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ys.core.model.CoreDictionaries;
import org.ys.core.model.CoreDictionariesExample;

public interface CoreDictionariesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    long countByExample(CoreDictionariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    int deleteByExample(CoreDictionariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long coreDictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    int insert(CoreDictionaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    int insertSelective(CoreDictionaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    List<CoreDictionaries> selectByExample(CoreDictionariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    CoreDictionaries selectByPrimaryKey(Long coreDictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CoreDictionaries record, @Param("example") CoreDictionariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CoreDictionaries record, @Param("example") CoreDictionariesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CoreDictionaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CoreDictionaries record);
    
    List<CoreDictionaries> listCoreDictionariesByDictGroupId(Long coreDictGroupId);
    
    List<CoreDictionaries> listCoreDictionariesByDictGroupCode(String dictGroupCode);
}