package org.ys.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ys.core.model.CoreDictionariesGroup;
import org.ys.core.model.CoreDictionariesGroupExample;

public interface CoreDictionariesGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    long countByExample(CoreDictionariesGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    int deleteByExample(CoreDictionariesGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long coreDictGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    int insert(CoreDictionariesGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    int insertSelective(CoreDictionariesGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    List<CoreDictionariesGroup> selectByExample(CoreDictionariesGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    CoreDictionariesGroup selectByPrimaryKey(Long coreDictGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CoreDictionariesGroup record, @Param("example") CoreDictionariesGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CoreDictionariesGroup record, @Param("example") CoreDictionariesGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CoreDictionariesGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dictionaries_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CoreDictionariesGroup record);
}