package org.ys.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ys.core.model.CoreDept;
import org.ys.core.model.CoreDeptExample;

public interface CoreDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    long countByExample(CoreDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    int deleteByExample(CoreDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long coreDeptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    int insert(CoreDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    int insertSelective(CoreDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    List<CoreDept> selectByExample(CoreDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    CoreDept selectByPrimaryKey(Long coreDeptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CoreDept record, @Param("example") CoreDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CoreDept record, @Param("example") CoreDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CoreDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CoreDept record);
}